test: support node 4
The `mock-fs` does not support `require` for Node.js 4.

Because of this test failed with error:

```
Cannot find module 'path/to/file.js
```